displayName=Clue Details
author=Zoinkwiz,TheLope
description=Provides details and personalisable highlighting for clues on the floor
tags=clue,overlay
plugins=com.cluedetails.ClueDetailsPlugin
version=2.8.1.4
build=standard
